apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: null
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: promptops-runner
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - nodes/proxy
      - nodes/stats
      - pods
      - replicationcontrollers
      - services
      - configmaps
      - serviceaccounts
      - events
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete

  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - statefulsets
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update

  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - delete

  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list

  - nonResourceURLs: ["/metrics"]
    verbs:
      - get

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]

  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
