apiVersion: v1
kind: ServiceAccount
metadata:
  name: promptops-runner
  namespace: promptops
# if running on eks, you can bind a role like this
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::account-id:role/role-name
